---
title: "Regression_Chla_GEE"
author: "Kislik et al"
date: "3/8/2022"
output: html_document
---

```{r}
library(ggplot2)
```

Read in the Data
```{r}
Data <- read.csv("2016_2020_15m_Copco_GEE.csv", header = TRUE)

colnames(Data)[1] <- "Sample_Date"
colnames(Data)
```

Create a Non-Linear Regression 
    ~(NDVI_Mean, NDCI_Mean, B4B8A_Mean, B3B2_Mean)~
```{r}

#CHANGE VARIABLE HERE - NDCI_Mean, NDVI_Mean, B4B8A_Mean, B3B2_Mean
Index <- Data$NDCI_Mean

ChlA <- Data$ChlA

model <- lm(Index ~ ChlA + I(ChlA^2) + I(ChlA^3))
summary(model)
```


Root Mean Squared Error
```{r}
RSS <- c(crossprod(model$residuals))
MSE <- RSS / length(model$residuals)
RMSE <- sqrt(MSE)
RMSE 
```

~Plots~

Regression Equation
```{r}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point(size = 3) +
  stat_smooth(method = "glm", formula=y~I(x^4), col = "#990000") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```
Helpful information: https://sejohnston.com/2012/08/09/a-quick-and-easy-function-to-plot-lm-results-in-r/


Plot the Non-Linear Regression
```{r}
model2 <- ggplotRegression(lm(Index ~ ChlA + I(ChlA^2) + I(ChlA^3))) +
  ylab("Chl-a (ug/L)") +
  xlab("NDCI") + 
  theme(axis.title.x = element_text(face="bold", colour="black", size=15),
           axis.text.x  = element_text(angle=0, vjust=0.5, size=13)) + 
  theme(axis.title.y = element_text(face="bold", colour="black", size=15),
           axis.text.y  = element_text(angle=0, vjust=0.5, size=13)) +
  theme(axis.text.x=element_text(angle = 0, hjust = 0)) + 
  theme(axis.text.y=element_text(angle = 0, hjust = 0)) +
  theme(axis.title.x = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
  theme(axis.text.x = element_text(margin = margin(t = 5, r = 5, b = 10, l = 5)))

model2

```
